---
title: "palm-oil-product-census"
author: "Emilio M. Bruna"
date: "10/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Part II: Palm Oil Products Survey**
https://www.treehugger.com/sneaky-names-palm-oil-4858743  
1. Elaeis guineensis
2. Etyl palmitate
3. Glyceryl
4. Hydrogenated palm glycerides
5. Octyl palmitate
6. Palm fruit oil
7. Palm kernel
8. Palm kernel oil
9. Palm stearine
10. Palmate
11. Palmitate
12. Palmitic acid
13. Palmitoyl oxostearamide
14. Palmitoyl tetrapeptide-3
15. Palmityl alcohol
16. Palmolein
17. Sodium kernelate
18. Sodium laureth sulfate
19. Sodium lauryl lactylate/sulphate
20. Sodium lauryl sulfate
21. Sodium palm kernelate
22. Stearate
23. Stearic acid
24. Vegetable fat
25. Vegetable oil

**Note that some of these, e.g., 22-25, can be derived from other coconut and other plant oils.**
(actually closer to 200 https://orangutanalliance.org/whats-the-issue/alternative-names-for-palm-oil/
)

some of the products: https://www.geographypods.com/palm-oil--me.html

Only a few manufacturers – mostly in the organic sector – label their products as containing palm oil and palm fat. Most companies disguise it, referring to it as “vegetable oils and fats”.

English and latin names for palm oilLikely to be palm oil Palm oil kernel Vegetable oil (if the product contains saturated fats, it's most likely palm oil) Palmitate / palmate Ingredient lists containing “stearate, stearyl” Elaeis gunieensis Ingredient lists containing the words “cetyl, cetearyl” Hydrated palm ­gylcerides hexadecanoic Sodium lauryl sulphate (SLS), sodium laureth sulphate, sodium dodecyl sulphate, (SDS or NaDS) sodium Palmitic acid Calcium stearoyl lactylate steareth -2, steareth -20 emulsifier 422, 430-36, 465-67, 470-8, 481-483

Source: http://www.orangutan.org.au/palm-oil

The largest palm oil producers:Major palm oil traders:The largest individual consumers of palm oil: Wilmar, IOI and Sinar Mas Cargill, Archer Daniels Midland (ADM) Unilever, Nestlé, Procter & Gamble and Henkel
According to its own figures, the Unilever Group alone consumes 1.6 million tons of palm oil every year (2008).

One way consumers can protect the rainforest is to avoid palm oil. For a list of palm oil-free products, visit
http://www.ethicalconsumer.org/shoppingethically/palmoilfreelist.aspx


How many of the products have the RSPO https://rspo.org/palmtrace or Rain Forest Alliance label? https://www.treehugger.com/what-does-rainforest-alliance-certification-mean-palm-oil-4856474
