---
title: "word_cloud"
author: "Emilio M. Bruna"
date: "8/25/2021"
output: html_document
---

For more info on word-clouds see [this tutorial](https://www.geeksforgeeks.org/generating-word-cloud-in-r-programming/)




```{r setup, include = FALSE,include = FALSE, echo = FALSE, message = FALSE, warning = FALSE}


# install the required packages
# install.packages("tm")		 # for text mining
# install.packages("SnowballC") # for text stemming
# install.packages("wordcloud") # word-cloud generator
# install.packages("RColorBrewer") # color palettes

# load the packages
library("tm")
library("tidytext")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("tidyverse")
library(stopwords)

```

```{r cleanup, include = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
# word<-read_csv("./class_materials/projects_and_code/free-list-word-cloud/2022/words_2022.csv") %>% 

word<-read_csv("./class_materials/projects_and_code/free-list-word-cloud/2022/words_2022.csv") %>% 
  separate(words,c(letters[seq(1:8)]),sep=",") %>% 
  pivot_longer(everything(),
    names_to = "word",) %>% 
  select(-word) %>% 
  rename(word=value) %>% 
  mutate(word=tolower(word)) %>% 
  mutate(word=trimws(word)) %>% 
  mutate(word=gsub('\\', "", word, fixed = TRUE)) %>% 
  arrange(word) %>% 
  drop_na() %>% 
  mutate(word=as.factor(word))
# write_csv(word, "./class_materials/free-list-word-cloud/2022/cleanwords_2022.csv")
write_csv(word, "./class_materials/projects_and_code/free-list-word-cloud/2022/cleanwords_2022.csv")
```



```{r cleanup2,include = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
# wordcloud<-read_csv("./class_materials/free-list-word-cloud/2022/post_openrefine_words_2022.csv") %>%
wordcloud<-read_csv("./class_materials/projects_and_code/free-list-word-cloud/2022/post_openrefine_words_2022.csv") %>%
  select(word2) %>% 
  mutate(word2=gsub(" ",".",word2)) %>% 
  arrange() %>% 
mutate(word2 = case_when(
    word2 == "big/tall.trees" ~ "large.trees",
    word2 == "cats/big.animals" ~ "big.animals",
    word2 == "threatened.by.humans/industry" ~ "threatened",
    word2 == "the.amazon" ~ "amazon",
    TRUE ~ word2
  )) %>% 
  add_row(word2 = "cats")



unique1<- wordcloud %>% summarize(n_distinct(word2))
  
```







<!-- text = readLines(file.choose()) -->
```{r fig1,echo = FALSE, message = FALSE, warning = FALSE}

text<-tolower(wordcloud$word2)
docs = Corpus(VectorSource(text))   

# Convert the text to lower case
docs = tm_map(docs, 
content_transformer(tolower))


# Remove numbers
docs = tm_map(docs, removeNumbers)
  
# Remove white spaces
docs = tm_map(docs, stripWhitespace)



dtm = TermDocumentMatrix(docs)

m = as.matrix(dtm)
v = sort(rowSums(m), decreasing = TRUE)
d = data.frame(word = names(v), freq = v)
head(d, 10)


document_tm_clean <- removeSparseTerms(dtm, 0.8)
document_tm_clean_mat <- as.matrix(document_tm_clean)

 
# # Graph 3: commonality word cloud : first top 2000 common words across classes
# png("#103_commonality_wordcloud.png", width = 480, height = 480)
# commonality.cloud(document_tm_clean_mat, max.words=200, random.order=FALSE)
# dev.off()


wc_fig<-wordcloud(words = d$word,
		freq = d$freq,
		min.freq = 1,
		max.words = 200,
		random.order = FALSE,
		random.color=FALSE,
		# rot.per = 0.35,
		rot.per = 0,
		colors = brewer.pal(8, "Spectral"))
		# colors = brewer.pal(8, "Dark2"))
```


Word Cloud - Week 1, unique words: `r unique1`


```{r setup2, include = FALSE,include = FALSE, echo = FALSE, message = FALSE, warning = FALSE}


# word<-read_csv("./class_materials/projects_and_code/free-list-word-cloud/2022/words_final_2022.csv") %>% 
word<-read_csv("./2022/words_final_2022.csv") %>% 
  select(word=9) %>% 
  rename("words"=1) %>% 
  separate(words,c(letters[seq(1:8)]),sep=",") %>% 
  # select(words) %>% 
  pivot_longer(everything(),
    names_to = "word",) %>% 
  select(-word) %>% 
  rename(word=value) %>% 
  mutate(word=tolower(word)) %>% 
  mutate(word=trimws(word)) %>% 
  mutate(word=gsub('\\', "", word, fixed = TRUE)) %>% 
  arrange(word) %>% 
  drop_na() 
  

word$word<-gsub("biodiverse" , "biodiversity",word$word)
word$word<-gsub("canopies" , "canopy",word$word)
word$word<-gsub("canopies of large trees" , "canopy",word$word)
word$word<-gsub("carbon sinks" , "carbon sink",word$word)
word$word<-gsub("cattle ranches" , "cattle ranching",word$word)
word$word<-gsub("deforestation- losing them" , "deforestation",word$word)
word$word<-gsub("diverse wildlife" , "biodiversity",word$word)
word$word<-gsub("diverse" , "biodiversity",word$word)
word$word<-gsub("exploitation" , "exploited",word$word)
word$word<-gsub("high biodiversity" , "biodiversity",word$word)
word$word<-gsub("importance" , "important",word$word)
word$word<-gsub("indigenous" , "indigenous people",word$word)
word$word<-gsub("\"blood monkey\"" , "Blood Monkey",word$word)
word$word<-gsub("natives" , "indigenous people",word$word)
word$word<-gsub("palm oil and beef" , "palm oil",word$word)
word$word<-gsub("palm oil and beef" , "beef",word$word)
word$word<-gsub("rich in species" , "biodiversity",word$word)
word$word<-gsub("rich" , "biodiversity",word$word)
word$word<-gsub("richness" , "biodiversity",word$word)
word$word<-gsub("tucan" , "toucan",word$word)
word$word<-gsub("wet and rainy" , "rainy",word$word)
word$word<-gsub("biodiversity" , "(bio)diversity",word$word)

word<-word %>% 
  mutate(word = case_when(
    word == "diversity" ~ "(bio)diversity",
    word == "(bio)diversityness" ~ "(bio)diversity",
    TRUE ~ word
  )) %>% 
   add_row(word = "wet")
 


# write_csv(word, "./class_materials/projects_and_code/free-list-word-cloud/2022/cleanwords_2022_edited.csv")
write_csv(word, "./2022/cleanwords_final_2022_edited.csv")
```


```{r cleanup3,include = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
# wordcloud<-read_csv("./class_materials/projects_and_code/free-list-word-cloud/2022/cleanwords_final_2022_edited.csv") %>%
wordcloud<-read_csv("./2022/cleanwords_final_2022_edited.csv") %>%
  select(word) %>% 
  mutate(word=gsub(" ",".",word)) %>% 
  arrange()
unique2<- wordcloud %>% summarize(n_distinct(word))
  
```







<!-- text = readLines(file.choose()) -->
```{r fig2,echo = FALSE, message = FALSE, warning = FALSE}

text<-tolower(wordcloud$word)
docs = Corpus(VectorSource(text))   

# Convert the text to lower case
docs = tm_map(docs, 
content_transformer(tolower))


# Remove numbers
docs = tm_map(docs, removeNumbers)
  
# Remove white spaces
docs = tm_map(docs, stripWhitespace)



dtm = TermDocumentMatrix(docs)

m = as.matrix(dtm)
v = sort(rowSums(m), decreasing = TRUE)
d = data.frame(word = names(v), freq = v)
head(d, 10)


document_tm_clean <- removeSparseTerms(dtm, 0.8)
document_tm_clean_mat <- as.matrix(document_tm_clean)

 
# # Graph 3: commonality word cloud : first top 2000 common words across classes
# png("#103_commonality_wordcloud.png", width = 480, height = 480)
# commonality.cloud(document_tm_clean_mat, max.words=200, random.order=FALSE)
# dev.off()


wc_fig_final<-wordcloud(words = d$word,
		freq = d$freq,
		min.freq = 1,
		max.words = 200,
		random.order = FALSE,
		random.color=FALSE,
		# rot.per = 0.35,
		rot.per = 0,
		# colors = brewer.pal(8, "Dark2"))
		colors = brewer.pal(8, "Spectral"))
    # colors = "red")

```


Word Cloud - Week 16, unique words: `r unique2`




