---
title: 'IDS 2935 - What is a Tropical Rain Forest?'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{What is a TRF?, p. \thepage}
- \fancyhead[L]{IDS 2935 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output: html_document
#   output:
#   pdf_document: default
#   html_document:
#     df_print: paged
#   rmdformats::robobook: default
# editor_options: 
#   markdown: 
#     wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1: _What_ are rain forests?

The next section will dive into two big questions: *What* are rain forests and *Where* are rain forests.

<!-- It took the entire 1 hour session to watch the videos and respond to the questions. It will go faster if they watch the videos in advance next time, but this entire day should be devoted to "what is a rain forest" (structure, precipitation, etc.) -->

Watch the following 360$^\circ$  video of a Longleaf Pine (LLP) Forest at the Jones Ecological Research Center, which is located approx. 200 miles from UF in southern Georgia. Be sure to rotate the video and look all around, including at the treetops (i.e., the ‘canopy’) and down at the forest floor. Note: Turn off the volume

* [Longleaf Pine Forest](https://www.youtube.com/watch?v=kRD1CpQOF7Q) 

Now do the same thing with the following:

At least the first 3:50 of this 360$^\circ$ video from the Northeastern Amazon. **_Note: Turn off the volume_**

* [Amazon Forest](https://www.youtube.com/watch?v=5JvJCvdqvYs)
    
<!-- sana daily climatiology pecip: https://svs.gsfc.nasa.gov/4759 -->

Then these three videos taken at different heights of the rain forest

* [Video 1](https://youtu.be/jpUtVi9g004)  

* [Video 2](https://youtu.be/eS1RQVe1tPg)   

* [Video 3](https://youtu.be/za6Cn2i2wQI)  


Compare with your table how these forests are “built”, i.e., their “structure”. To guide your discussion, respond to the following questions. What do you notice when comparing the LLP Forest with the Amazon Forest about:


> 3.1 The relative height and diameter of trees  

> 3.2 The structure of the forest canopy ("roof")  

> 3.3 The “complexity” of the forest structure as you move from the Canopy to the Forest Floor  

<!-- Not as obiously distinct an herbaceous or understory layer -->
<!-- not a distinct layer, much of what is there is hanging out waiting for an * ortunity to overcome one of its 3 limiting resources. What do you think these are? *  -->


> 3.4 The different types of plants in each forest type: what types of plants do you see other than trees?  

> 3.5 The major resources plants need to grow? (what are those? If you're not sure, ask)  

<!-- * - Light, Water, Nutrients --> 

Each answer should include observations from each forest type. For example, "3.1: The trees in LLP are ____ and ____, whereas the trees in the rain forest are _____, _______, and _______."

## Submission

Submit your answers in here. You can discuss and come up with answers as a group, but each person must submit individual responses to the questions.
