---
title: "Course Meetings, Location, & Weekly Schedule"
author: "Emilio M. Bruna"
date: "7/9/2021"
output: pdf_document
# output: pdf_document
draft: false
subtitle: ""
weight: 3
---

```{r setup_schedule, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# library(gridExtra)
library(kableExtra)
# library(egg)
# library(magick)
# library(citr)
```

### Weekly Schedule
      
```{r course_calendar, echo=FALSE,message = FALSE,warning=FALSE}
calendar <- read_csv("./course_schedule_short.csv") %>% 
  # calendar <- calendar %>% 
  mutate(Week=paste(Week1,Week,sep=" ")) %>% 
  select(-X1,-Week1) %>% 
  select(Week,Date,Topic, `Read Before Class`) %>% 
  replace_na(list(Date="",Week="", Topic="",`Read Before Class`="", `Watch Before Class`=""))

calendar$Week <- gsub("NA NA","", calendar$Week)
calendar$Week <- gsub("NA Final Exam","", calendar$Week)
# names(calendar) <- c("","","")




kable(calendar,
      # digits = 2,
      align="cclll",
      format="html",
      row.names = FALSE,
      escape= TRUE,
      booktabs=T,
      linesep = "",
      ) %>% 
  kable_paper(full_width = F) %>%
  column_spec(1, bold = F, border_right = T) %>%
  column_spec(2, width = "5em", background = "white",border_right = T) %>% 
    pack_rows("WHY ARE WE FASCINATED BY TROPICAL RAIN FORESTS?", 1, 6) %>%
  pack_rows("THE ECOLOGY & EVOLUTION OF TROPICAL RAIN FORESTS", 7, 21) %>%
  pack_rows("THE DRIVERS AND IMPACTS OF DEFORESTATION", 22, 30) %>%
  pack_rows("THE FUTURE OF TROPICAL RAIN FORESTS", 31, 48) %>%
  pack_rows("Finals Week", 49, 49) %>%
  kable_styling(bootstrap_options = c("hover"),
                full_width = T,
                latex_options="scale_down",
                font_size = 14,
                position = "left")

```