---
title: 'IDS 2935 - Historical Narratives: In-class Activity'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Lit and Poetry (In-class), p. \thepage}
- \fancyhead[L]{IDS 2935 - Rain Forests (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
editor_options: 
  markdown: 
    wrap: 72
    
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_dir = "./static/uploads")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Historical Narratives and the Depiction of Tropical Rain Forests and People    
\vspace{0.3cm}

Whether or not you realize it, every time you reads a passage of text you are breaking it apart into its unique elements - words - and then analyzing the words and their arrangement into sentences to infer what the author hopes to convey. This interpretation will be shaped in part by your experiences, the cultural environment in which you were raised, and the sociopolitical moment in which they are read.  

As readers we usually do this *"Text Analysis"* subconsciously, but we can also step back and do it explicitly: we can extract keywords from the text and analyze them to draw conclusions about the messages conveyed by an author's choices. For instance, we can analyze if the words used in a passage have meanings that are typically "positive", "negative", or "neutral", and from that conclude what a reader of a passage would conclude about the subject matter This is called *Sentiment Analysis*

**You will be doing some simple Sentiment Analysis on reports written by some of the first Europeans to travel through (_i.e._, 'explore') tropical rain forests.** We will then use your results to collectively identify the major themes these historical reports established about tropical forests and the people that lived there. In future sessions, we will attempt to determine if these themes are reflected in over 500 years of cultural expression ranging from poetry to comic books _(spoiler alert: they are)_.

### Instructions - Part 1 (Do on your own, bring to the next session)  

1. Download the .pdf file of historical texts and images: [[link to file](https://ids2935.netlify.app/uploads/historical_narratives.pdf)] and the spreadsheet for recording data [[link to download](https://ids2935.netlify.app/uploads/narrative_score_sheet.xlsx)].

1. Read (or examine) each text or image. As you do so, mark or note especially powerful descriptions of places, people, or behavior. 

1. Enter these words or phrases into this spreadsheet. Be sure to note from which text they came (Item1, Item2, etc.)

1. Assign each of these words/phrases a score based on if they are 'positive (+1)', 'negative (-1)', or 'neutral (0)'.

1. Upload the spreadsheet with the words/phrases and their scores to Canvas when finished

<!-- 5. Sometimes the things _left out_ by the author are as informative as the things they _did_ say. Can you infer anything from what *wasn't* said? -->


**Once you have read and scored all the passages, take a step back: ** 

> Can you identify some major themes (= *narratives*) about Tropical Rain Forests and the people living in them that emerge from these passages? Put another way, what would you conclude about thee places and people if you were reading these passages *at the time they were written*? 

We will compare conclusions as a group in the next session, so _bring your marked texts, score sheets, and conclusions and come prepared to discuss them with your classmates_

<!-- **<<revision for v 2.0; we got through only part 1. if you delete the lecture slide and do it as a video, you might get through the lit. but I rec doing part 1 only, then doing the lit/poetry as part of culture.>>** -->
